name: Frontend Standards | By Adam Silver
markdown: redcarpet
highlighter: pygments
permalink: /articles/:title/
url: http://adamsilver.github.io/sponda/
include: ['_pages']
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]